version: "3"

services:
  phoenix:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - rocket_pay_postgres_data:/var/lib/postgresql/data

volumes:
  rocket_pay_postgres_data: